[tool.poetry]
name = "spiffworkflow-arena"
version = "0.0.0"
description = "Spiffworkflow Arena"
authors = ["Jason Lantz <sartography@users.noreply.github.com>"]
license = "LGPL"
readme = "README.md"
homepage = "https://github.com/sartography/spiffworkflow-arena"
package-mode = false
repository = "https://github.com/sartography/spiffworkflow-arena"
classifiers = [
    "Development Status :: 4 - Beta",
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"

[tool.poetry.dev-dependencies]
pre-commit = "^3.7.1"
pre-commit-hooks = "^4.6.0"
ruff = "^0.5.5"

[tool.poetry.group.dev.dependencies]
tomli = "^2.0.1"
git-debranch = "^0.1.9"
