version: '3.8'
services:
  spiffworkflow-frontend:
    container_name: spiffworkflow-frontend
    # command: tail -f /etc/hostname
    build:
      context: .
    environment:
      - APPLICATION_ROOT=/
      - PORT0=7001
      - SPIFFWORKFLOW_FRONTEND_RUNTIME_CONFIG_TASK_METADATA='[{"name":"due_days_after_open","label":"DueDaysAfterOpen","description":"Numberofdaysafteropeninguntildue"},"due_days_before_closing"]'
      # - SPIFFWORKFLOW_FRONTEND_RUNTIME_CONFIG_TASK_METADATA="HEY"
    ports:
      - '7001:7001'
