groups:
  admin:
    users: [jakub, kb, alex, dan, mike, jason, amir, jarrad, elizabeth, jon]

  finance:
    users: [harmeet, sasha]

  hr:
    users: [manuchehr]

permissions:
  admin:
    groups: [admin]
    users: []
    allowed_permissions: [create, read, update, delete, list, instantiate]
    uri: /*

  finance-admin:
    groups: [finance]
    users: []
    allowed_permissions: [create, read, update, delete]
    uri: /v1.0/process-groups/finance/*

  read-all:
    groups: [finance, hr, admin]
    users: []
    allowed_permissions: [read]
    uri: /*
