name: Build and Deploy Connector Proxy - Async Http
on:
  push:
    paths:
      - connector-proxies/async-http/**
      - .github/workflows/connector-proxy-async-http.yml
    branches:
      - main
      - deploy
jobs:
  deploy:
    name: Deploy Connector Proxy - Async Http
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy connector-proxies/async-http --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_CP_AH_API_TOKEN }}
